#! /bin/sh

#  ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓ ██▀███   ▄████▄
# ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█
# ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄
# ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒
# ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░
# ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░
# ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  ░▒ ░ ▒░  ░  ▒
#  ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     ░░   ░ ░
#  ░            ░               ░           ░      ░     ░ ░
#       ░                                                ░

bspc monitor -d term web files video

bspc config border_width         2
bspc config window_gap          25
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20

bspc rule -a Pcmanfm			desktop='^3' follow=on
bspc rule -a Lxappearence		desktop='^4' follow=on

bspc rule -a surf				state=floating follow=on
bspc rule -a tabbed				state=floating follow=on
bspc rule -a IceCat				state=floating follow=on
bspc rule -a mpv				state=floating follow=on
bspc rule -a Sxiv				state=floating follow=on
bspc rule -a URxvt				state=floating follow=on
bspc rule -a dropdown			state=floating follow=on

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true


# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$fg"
bspc config presel_feedback_color "$color7"

# execute some nice programs on startup.
. "${HOME}/.config/bspwm/autostart"
