#! /bin/sh

# bspc monitor
bspc monitor -d 1 2 3 4


# bspwm config
# ----------------------------------------

bspc config border_width         3
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   blue
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config top_padding          25
bspc config bottom_padding       25
bspc config left_padding         20
bspc config right_padding        20


# Border Colors
# ----------------------------------------

bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$fg"
bspc config presel_feedback_color "$color7"


# Rules
# ----------------------------------------

bspc rule -a Pcmanfm			desktop='^3' follow=on
bspc rule -a Lxappearence		desktop='^4' follow=on
bspc rule -a Tilix				desktop='^1' follow=on
bspc rule -a qutebrowser		desktop='^2' follow=on
bspc rule -a mpv				desktop='^3' state=fullscreen follow=on
bspc rule -a Sxiv				state=fullscreen follow=on
bspc rule -a dropdown			state=floating follow=on


# execute some nice programs on startup.
. "${HOME}/.config/bspwm/autostart"
